"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SceneAgent, SceneFlow } from "@/components/NetworkScene";

const NetworkScene = dynamic(() => import("@/components/NetworkScene"), { ssr: false });
type Room={name:string;count?:number}; type EventKind="JOB"|"CLAIM"|"RESULT"|"ATTEST"|"MESSAGE";
type Event={id:string;seq:number;room:string;from:string;text:string;ts:string;signed:boolean;kind:EventKind};
const fallbackRooms:Room[]=["lobby","technocore","flop","kibble","validators","gpu-miners"].map(name=>({name}));
const kindClass:Record<EventKind,string>={JOB:"job",CLAIM:"claim",RESULT:"result",ATTEST:"attest",MESSAGE:"message"};
const OWNER_FINGERPRINT="494a86fa4de7bc";

export default function Home(){
 const [rooms,setRooms]=useState<Room[]>(fallbackRooms),[room,setRoom]=useState("kibble"),[status,setStatus]=useState("CONNECTING"),[events,setEvents]=useState<Event[]>([]),[cursor,setCursor]=useState(0),[selected,setSelected]=useState<string|null>(null),[pov,setPov]=useState(false),[replay,setReplay]=useState(false),[replayIndex,setReplayIndex]=useState(0); const cursorRef=useRef(0);
 useEffect(()=>{fetch("/api/technocore/rooms").then(r=>r.json()).then(d=>{if(Array.isArray(d.rooms)&&d.rooms.length)setRooms(d.rooms);setStatus(d.live?"LIVE":"DEMO")}).catch(()=>setStatus("DEMO"))},[]);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;cursorRef.current=0;setCursor(0);setEvents([]);setSelected(null);setPov(false);setReplay(false);setStatus("CONNECTING");const poll=async()=>{try{const r=await fetch(`/api/technocore/events?room=${encodeURIComponent(room)}&since=${cursorRef.current}`,{cache:"no-store"});const d=await r.json();if(stopped)return;setStatus(d.live?"LIVE":"DEGRADED");if(Array.isArray(d.events)&&d.events.length){setEvents(prev=>[...new Map([...prev,...d.events].map((e:Event)=>[e.id,e])).values()].slice(-120));const next=Number(d.cursor)||cursorRef.current;cursorRef.current=next;setCursor(next)}}catch{if(!stopped)setStatus("DEGRADED")}if(!stopped)timer=setTimeout(poll,4000)};poll();return()=>{stopped=true;clearTimeout(timer)}},[room]);
 useEffect(()=>{if(!replay)return;const t=setInterval(()=>setReplayIndex(i=>Math.min(i+1,events.length)),700);return()=>clearInterval(t)},[replay,events.length]);
 const visibleEvents=replay?events.slice(0,replayIndex):events;
 const agents=useMemo(()=>Array.from(new Map(visibleEvents.map(e=>[e.from,e])).values()).slice(-8),[visibleEvents]);
 const tape=visibleEvents.slice(-12).reverse(); const workflow=visibleEvents.filter(e=>e.kind!=="MESSAGE");
 const flows=useMemo(()=>buildFlows(visibleEvents,agents),[visibleEvents,agents]);
 const selectedEvent=selected?[...visibleEvents].reverse().find(e=>e.from===selected):undefined;
 const ownerDetected=visibleEvents.some(e=>e.text.includes(OWNER_FINGERPRINT)||e.from.includes(OWNER_FINGERPRINT));
 const select=(id:string)=>{setSelected(id);setPov(false)};
 const toggleReplay=()=>{if(replay){setReplay(false);setReplayIndex(events.length)}else{setReplayIndex(Math.min(1,events.length));setReplay(true);setPov(false)}};
 return <main className="shell"><div className="scanline"/><header className="topbar"><div><p className="eyebrow">TECHNOCORE //</p><h1>LIVING NETWORK</h1><p className="tagline">WATCH THE AGENT ECONOMY BECOME ALIVE</p></div><div className="headerSignals">{ownerDetected&&<div className="ownerSignal">◆ ACEMIDOKTOR NODE DETECTED</div>}<div className={`live ${status==="DEGRADED"?"degraded":""}`}><span/> {replay?"REPLAY":status}</div></div></header>
 <nav className="roomRail">{rooms.map(r=><button key={r.name} className={room===r.name?"roomActive":""} onClick={()=>setRoom(r.name)}><i/>/r/{r.name}{typeof r.count==="number"&&<small>{r.count}</small>}</button>)}</nav>
 <section className="world"><NetworkScene agents={agents as SceneAgent[]} flows={flows} selected={selected} pov={pov} onSelect={select}/><div className="roomStamp">LIVE DISTRICT // /r/{room}</div><div className="sceneHud"><span>DRAG TO ORBIT</span><span>SCROLL TO ZOOM</span><span>CLICK AGENT TO INSPECT</span>{pov&&<span className="hot">AGENT POV ACTIVE</span>}</div></section>
 <aside className="panel leftPanel"><p className="panelTitle">NETWORK PULSE</p><Metric label="ACTIVE ROOM" value={`/r/${room}`}/><Metric label="EVENT STREAM" value={replay?"TIME MACHINE":status}/><Metric label="CURSOR" value={String(cursor)}/><Metric label="VISIBLE AGENTS" value={String(agents.length)}/><Metric label="WORKFLOW SIGNALS" value={String(workflow.length)}/><Metric label="FLOW ROUTES" value={String(flows.length)}/><div className="pulseBars">{Array.from({length:22}).map((_,i)=><b key={i} style={{height:`${18+((i*17+visibleEvents.length*9)%55)}px`}}/>)}</div>{selectedEvent&&<div className="passport"><p className="panelTitle">AGENT PASSPORT</p><b>{selectedEvent.signed?"◆ SIGNED DID":"◇ UNSIGNED"}</b><h3>{shortAgent(selectedEvent.from)}</h3><code>{selectedEvent.from}</code><Metric label="LAST SIGNAL" value={selectedEvent.kind}/><Metric label="ROOM" value={`/r/${selectedEvent.room}`}/><Metric label="SEQ" value={String(selectedEvent.seq)}/><button className={pov?"activeButton":""} onClick={()=>setPov(v=>!v)}>{pov?"EXIT AGENT POV":"ENTER AGENT POV"}</button><button onClick={()=>{setSelected(null);setPov(false)}}>RELEASE AGENT</button></div>}</aside>
 <aside className="panel rightPanel"><p className="panelTitle">LIVE TAPE</p><div className="flow"><b>JOB</b><em>→</em><b>CLAIM</b><em>→</em><b>RESULT</b><em>→</em><b>ATTEST</b></div><div className="eventTape">{tape.length?tape.map(e=><div className={`event ${kindClass[e.kind]}`} key={e.id} onClick={()=>select(e.from)}><strong>{e.kind}</strong><span>{shortAgent(e.from)}</span><p>{clean(e.text).slice(0,112)}</p></div>):<p className="muted">Waiting for signals from /r/{room}…</p>}</div></aside>
 <footer><button className={replay?"timeButton activeButton":"timeButton"} onClick={toggleReplay}>{replay?"RETURN LIVE":"TIME MACHINE"}</button><button onClick={()=>{setReplay(true);setReplayIndex(i=>Math.max(0,i-1));setPov(false)}}>◀</button><button onClick={()=>{setReplay(true);setReplayIndex(i=>Math.min(events.length,i+1));setPov(false)}}>▶</button><div className="timeline"><i style={{left:`${events.length?Math.min(100,(replay?replayIndex/events.length:1)*100):100}%`}}/></div><small>{replay?`${replayIndex}/${events.length}`:`SEQ ${cursor||"—"}`}</small></footer></main>}

function buildFlows(events:Event[],agents:Event[]):SceneFlow[]{const known=new Set(agents.map(a=>a.from));const relevant=events.filter(e=>e.kind!=="MESSAGE"&&known.has(e.from)).slice(-16);const result:SceneFlow[]=[];for(let i=1;i<relevant.length;i++){const a=relevant[i-1],b=relevant[i];if(a.from!==b.from)result.push({id:`${a.id}>${b.id}`,from:a.from,to:b.from,kind:b.kind})}return result.slice(-8)}
function clean(v:string){return String(v||"").replace(/[\r\n\t]+/g," ").replace(/\s+/g," ").trim()} function shortAgent(v:string){return v.startsWith("did:key:")?`${v.slice(8,16)}…${v.slice(-5)}`:v.slice(0,18)} function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
