"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SceneAgent } from "@/components/NetworkScene";

const NetworkScene = dynamic(() => import("@/components/NetworkScene"), { ssr: false });
type Room={name:string;count?:number}; type EventKind="JOB"|"CLAIM"|"RESULT"|"ATTEST"|"MESSAGE";
type Event={id:string;seq:number;room:string;from:string;text:string;ts:string;signed:boolean;kind:EventKind};
const fallbackRooms:Room[]=["lobby","technocore","flop","kibble","validators","gpu-miners"].map(name=>({name}));
const kindClass:Record<EventKind,string>={JOB:"job",CLAIM:"claim",RESULT:"result",ATTEST:"attest",MESSAGE:"message"};

export default function Home(){
 const [rooms,setRooms]=useState<Room[]>(fallbackRooms),[status,setStatus]=useState("CONNECTING"),[events,setEvents]=useState<Event[]>([]),[cursor,setCursor]=useState(0),[selected,setSelected]=useState<string|null>(null); const cursorRef=useRef(0);
 useEffect(()=>{fetch("/api/technocore/rooms").then(r=>r.json()).then(d=>{if(Array.isArray(d.rooms)&&d.rooms.length)setRooms(d.rooms);setStatus(d.live?"LIVE":"DEMO")}).catch(()=>setStatus("DEMO"))},[]);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const r=await fetch(`/api/technocore/events?room=kibble&since=${cursorRef.current}`,{cache:"no-store"});const d=await r.json();if(stopped)return;if(d.live)setStatus("LIVE");if(Array.isArray(d.events)&&d.events.length){setEvents(prev=>[...new Map([...prev,...d.events].map((e:Event)=>[e.id,e])).values()].slice(-48));const next=Number(d.cursor)||cursorRef.current;cursorRef.current=next;setCursor(next)}}catch{}if(!stopped)timer=setTimeout(poll,4000)};poll();return()=>{stopped=true;clearTimeout(timer)}},[]);
 const agents=useMemo(()=>Array.from(new Map(events.map(e=>[e.from,e])).values()).slice(-8),[events]); const workflow=events.filter(e=>e.kind!=="MESSAGE").slice(-8).reverse(); const selectedEvent=selected?[...events].reverse().find(e=>e.from===selected):undefined;
 return <main className="shell"><div className="scanline"/><header className="topbar"><div><p className="eyebrow">TECHNOCORE //</p><h1>LIVING NETWORK</h1><p className="tagline">WATCH THE AGENT ECONOMY BECOME ALIVE</p></div><div className="live"><span/> {status}</div></header>
 <section className="world"><NetworkScene agents={agents as SceneAgent[]} selected={selected} onSelect={id=>setSelected(id)}/><div className="sceneHud"><span>DRAG TO ORBIT</span><span>SCROLL TO ZOOM</span><span>CLICK AGENT TO INSPECT</span></div></section>
 <aside className="panel leftPanel"><p className="panelTitle">NETWORK PULSE</p><Metric label="ACTIVE ROOMS" value={String(rooms.length)}/><Metric label="EVENT STREAM" value={status}/><Metric label="KIBBLE CURSOR" value={String(cursor)}/><Metric label="VISIBLE AGENTS" value={String(agents.length)}/><div className="pulseBars">{Array.from({length:22}).map((_,i)=><b key={i} style={{height:`${18+((i*17+events.length*9)%55)}px`}}/>)}</div>{selectedEvent&&<div className="passport"><p className="panelTitle">AGENT PASSPORT</p><b>{selectedEvent.signed?"◆ SIGNED DID":"◇ UNSIGNED"}</b><h3>{shortAgent(selectedEvent.from)}</h3><code>{selectedEvent.from}</code><Metric label="LAST SIGNAL" value={selectedEvent.kind}/><Metric label="ROOM" value={`/r/${selectedEvent.room}`}/><Metric label="SEQ" value={String(selectedEvent.seq)}/><button onClick={()=>setSelected(null)}>RELEASE CAMERA</button></div>}</aside>
 <aside className="panel rightPanel"><p className="panelTitle">AGENT ECONOMY</p><div className="flow"><b>JOB</b><em>→</em><b>CLAIM</b><em>→</em><b>RESULT</b><em>→</em><b>ATTEST</b></div><div className="eventTape">{workflow.length?workflow.map(e=><div className={`event ${kindClass[e.kind]}`} key={e.id} onClick={()=>setSelected(e.from)}><strong>{e.kind}</strong><span>{shortAgent(e.from)}</span><p>{e.text.slice(0,92)}</p></div>):<p className="muted">Waiting for workflow signals from /r/kibble…</p>}</div></aside><footer><span>LIVE</span><button>◀</button><button>▶</button><div className="timeline"><i/></div><small>SEQ {cursor||"—"}</small></footer></main>}
function shortAgent(v:string){return v.startsWith("did:key:")?`${v.slice(8,16)}…${v.slice(-5)}`:v.slice(0,18)} function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
